build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job:
  stage: test
  script:
    - python3 -m pytest .

deploy-prod:
  stage: deploy
  script:
    - python3 -u publish.py | python3 -u publish_bot.py > /dev/null